#!/bin/sh
# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" ;
alias snvim='sudo nvim'

# Core utils
alias ls='ls -hN --color=always --group-directories-first' ;
alias rm='rm -vI' ;
alias mv='mv -vi' ;
alias cp='cp -vi' ;
alias mkdir='mkdir -pv' ;
alias grep='grep --color=auto' ;
alias diff='diff --color=auto' ;
alias ip='ip -color=auto' ;
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Software specific aliases
alias yt='youtube-dl --add-metadata -i' ;
alias yta='yt -x -f bestaudio/best' ;
alias hex='nvim -b' ;
alias hexedit='hexedit --color' ;
alias popen='pass open -f' ;

# Config shortcuts
alias bib='nvim ~/documents/latex/bib/bibliografi.bib' ;
alias nzsh='nvim ~/.config/zsh/.zshrc' ;
alias nurls='nvim ~/.config/newsboat/urls' ;
alias nsxhkd='nvim ~/.config/sxhkd/sxhkdrc' ;

# Git
alias g='git' ;
alias gs='git status' ;
alias ga='git add' ;
alias gc='git commit' ;
alias gp='git push' ;
alias gpu='git pull' ;
alias grm='git rm' ;
alias gmv='git mv' ;

# Custom config locations
alias abook='abook -C "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook' ;
alias tmux='tmux -f "$XDG_CONFIG_HOME"/tmux/tmux.conf' ;
alias calcurse='calcurse -D ~/.config/calcurse/' ;
alias mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc' ;

# Mac specific aliases
#alias ls='ls -Gh' ;
#alias rm='rm -vi' ;
#alias mv='mv -vi' ;
#alias cp='cp -vi' ;
