#!/bin/sh
# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim='nvim' vimdiff='nvim -d' snvim='sudo nvim' ;

# Core utils
alias ls='ls -hFN --color=always --group-directories-first' ;
alias rm='rm -vI' ;
alias mv='mv -vi' ;
alias cp='cp -v' ;
alias mkdir='mkdir -pv' ;
alias grep='grep --color=auto' ;
alias diff='diff --color=auto' ;
alias ip='ip -color=always' ;
alias ..='cd ..' ;
alias ...='cd ../..' ;
alias ....='cd ../../..' ;

# Software specific aliases
alias yeet='sudo pacman -Rns' ;
alias yt='yt-dlp --add-metadata -i' ;
alias yta='yt-dlp -x -f bestaudio/best' ;
alias ftf='fzf-tmux -r'
alias hex='nvim -b' ;
alias hexedit='hexedit --color' ;
alias popen='pass open -f' ;
alias gotop='gotop -c cyberpunk_neon' ;
alias dosbox='dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf' ;
alias tmuxl='tmux list-sessions' ;
alias tmuxa='tmux attach-session -t' ;

# Config shortcuts
alias bib='nvim ~/dokumenter/latex/bib/bibliografi.bib' ;
alias nzsh='nvim ~/.config/zsh/.zshrc' ;
alias ninit='nvim ~/.config/nvim/init.vim' ;
alias nurls='nvim ~/.config/newsboat/urls' ;
alias nsxhkd='nvim ~/.config/sxhkd/sxhkdrc' ;

# Git
alias g='git' ;
alias gs='git status' ;
alias ga='git add' ;
alias gc='git commit -S' ;
alias gp='git push' ;
alias gpu='git pull' ;
alias grm='git rm' ;
alias gmv='git mv' ;

# Custom config locations
alias abook='abook -C "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook' ;
alias calcurse='calcurse -D ~/.config/calcurse/' ;
alias mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc' ;
alias irssi='irssi --config=/home/eirik/.config/irssi/config --home=/home/eirik/.local/share/irssi' ;

# Mac specific aliases
#alias ls='ls -Gh' ;
#alias rm='rm -vi' ;
#alias mv='mv -vi' ;
#alias cp='cp -vi' ;
