#!/bin/sh
alias h='cd ~/ && pwd && ls -A' ;
alias t='cd ~/Documents && pwd && ls -A' ;
alias d='cd ~/Documents && pwd && ls -A' ;
alias ma='cd ~/Documents/man && pwd && ls -A' ;
alias oF='cd ~/Documents/build/oF && pwd && ls -A' ;
alias i='cd ~/media/bilder && pwd && ls -A' ;
alias v='cd ~/media/video && pwd && ls -A' ;
alias iw='cd ~/media/bilder/wallpapers && pwd && ls -A' ;
alias m='cd ~/media/musikk && pwd && ls -A' ;
alias mp='cd ~/media/musikk/podcasts && pwd && ls -A' ;
alias dl='cd ~/Downloads && pwd && ls -A' ;

alias b='cd /opt/ && pwd && ls -A' ;
alias bdw='cd /opt/dwm && pwd && ls -A' ;
alias bdwb='cd /opt/dwm/dwmblocks && pwd && ls -A' ;
alias bdm='cd /opt/dmenu && pwd && ls -A' ;
alias bs='cd /opt/st && pwd && ls -A' ;
alias bsl='cd /opt/slock && pwd && ls -A' ;
alias bsu='cd /opt/surf && pwd && ls -A' ;
alias bf='cd /opt/ffmpeg && pwd && ls -A' ;
alias bof='cd /opt/of && pwd && ls -A' ;
alias p='cd ~/Documents/build/patching_dir && pwd && ls -A' ;

alias s='cd ~/Documents/synk && pwd && ls -A' ;
alias a='cd ~/Documents/synk/arbeid && pwd && ls -A' ;
alias ho='cd ~/Documents/synk/hobby && pwd && ls -A' ;
alias ap='cd ~/Documents/synk/arbeid/produksjoner && pwd && ls -A' ;
alias app='cd ~/Documents/artistic_practice/portfolio && pwd && ls -A' ;
alias apr='cd ~/Documents/artistic_practice/artistic_research && pwd && ls -A' ;

alias gr='cd ~/Documents && pwd && ls -A' ;
alias g.='cd ~/Documents/Dotfiles && pwd && ls -A' ;
alias gdw='cd ~/Documents/dwm && pwd && ls -A' ;
alias gdm='cd ~/Documents/dmenu && pwd && ls -A' ;
alias gst='cd ~/Documents/st && pwd && ls -A' ;
alias gsl='cd ~/Documents/slock && pwd && ls -A' ;
alias gsu='cd ~/Documents/surf && pwd && ls -A' ;

alias c='cd ~/.config && pwd && ls -A' ;
alias lb='cd ~/.local/bin && pwd && ls -A' ;
alias lbs='cd ~/.local/bin/scripts && pwd && ls -A' ;
alias lsh='cd ~/.local/share && pwd && ls -A' ;
alias lsp='cd ~/.local/share/password-store && pwd && ls -A' ;
alias lsg='cd ~/.local/share/gnupg && pwd && ls -A' ;
alias lsm='cd ~/.local/share/mail && pwd && ls -A' ;
alias vt='cd ~/.local/share/vifm/Trash && pwd && ls -A' ;

# Mac shortcuts
