#!/bin/sh
userresources=$HOME/.config/Xresources

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

~/.local/bin/scripts/.fehbg &
dwmblocks &
sxhkd &
xrdb ~/.config/Xresources &
unclutter &
xcompmgr &
dunst &
mpd &
remaps &
syncthing -no-browser &
protonmail-bridge --no-window &
expressvpn connect smart &

xinput disable SynPS/2\ Synaptics\ TouchPad &

exec dwm
